### ISSUE TITLE
Example docker run commands in the readme will not run as-is.

### ISSUE THREAD

**Issue by kburger** [FAIRDataTeam/OpenRefine-metadata-extension#29]
The README provides oneliner examples for `docker run` commands. The docker images do not contain a tag, so the default docker behaviour is to use `latest`. Running the example cli command will trigger an error since there is no `latest` tag (currently only `1.0.0-rc1` and `develop` tags). There should either be a `latest` tag, or the documentation should use the proper tag.

https://github.com/FAIRDataTeam/OpenRefine-metadata-extension/blob/59572d60f781e4db229fca2b69236c271e4a97b6/README.md#L29

https://github.com/FAIRDataTeam/OpenRefine-metadata-extension/blob/59572d60f781e4db229fca2b69236c271e4a97b6/README.md#L37

**Comment by MarekSuchanek** [comment]
I manually pushed `1.0.0-rc.1` as `latest` so it will work now. This won't be needed any time else because `latest` is set to be automatically built from `master` branch.

The rules were and are as follows:
* `vX.Y.Z[-whatever]` (tag) → `X.Y.Z[-whatever]`
* `develop` (branch) → `develop`
* `master` (branch) → `latest` (as all and only stable versions are in `master`)

Optionally, other development branches can be turned on easily for testing purposes...
